name: Auto Pull Request
on: [push]

permissions:
  contents: write

jobs:
  push-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Git user
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}
          git push --force-with-lease origin feature/test:refs/heads/feature/test

  auto-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          title: "Auto PR: Update from main"
          body: |
            This pull request was automatically generated by GitHub Actions.
          branch: auto-pr-branch
          base: main
