name: Auto Pull Request

on:
  push:
    branches:
      - 'feature/**'  # Trigger on pushes to branches starting with "feature/"

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Automated PR from feature branch
          title: 'Auto PR for ${{ github.ref_name }}'
          body: 'This pull request was created automatically from the pushed feature branch.'
          base: main   # Target branch for the PR
          branch: ${{ github.ref_name }}  # Source branch
